title: Gamer Assistants
baseline: esports player's assistant - it is me
description: Your writing maniac about esport business and expansion games and much more
baseurl: 'https://onlinemacizle.org/'
canonicalurl: false
theme: hyde
date:
  format: j F Y
  timezone: Europe/Paris
pagination:
  max: 5
  path: page
output:
  formats:
    netlify_redirects:
      extension: ''
      mediatype: text/plain
virtualpages:
  _redirects:
    output: netlify_redirects
  admin:
    layout: admin/index
    title: Content Manager (Netlify CMS)
    output: html
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
